### ISSUE TITLE
images folder not created

### ISSUE THREAD

**Issue by Krishnateja001** [leiDnedyA/qr-image-drop#16]
when the repo is cloned after setting up the project 
upload feature fails due to images folder not being created in the static/ 

returns: FileNotFoundError: [Errno 2] No such file or directory: 'static/images/d27a5ea4-910a-475a-8042-2ba0dfa46c7f_20240326121820_favicon.png'

**Comment by leiDnedyA** [comment]
thanks for submitting :)
