### ISSUE TITLE
Broken copy button

### ISSUE THREAD

**Issue by leiDnedyA** [leiDnedyA/qr-image-drop#55]

**Comment by leiDnedyA** [comment]
According to feedback, in some situations, the copy button doesn't work. However, when I test it the feature works fine. If anyone is able to reproduce the bug please let me know!

**Comment by gaiborjosue** [comment]
Hi @leiDnedyA, indeed, the copy button doesn't work when copying from an iPad. I tested it last week and had to use the native copy functionality from iOS.
